/// Flutter icons DashboardIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DashboardIcons
///      fonts:
///       - asset: fonts/DashboardIcons.ttf
///
/// 
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/widgets.dart';

class DashboardIcons {
  DashboardIcons._();

  static const _kFontFam = 'DashboardIcons';
  static const String? _kFontPkg = null;

  static const IconData clouds_flash = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drizzle = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_heavy = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sun = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mist = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData na = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
