include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true

analyzer:
  errors:
    top_level_function_literal_block: ignore
  exclude:
    - "lib/dashboard_icons.dart"
