include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    directives_ordering: true

analyzer:
  exclude:
    - "lib/dashboard_icons.dart"
